version: '3.3'

services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env

  api:
    build: .

    restart: always

    depends_on:
      - db

    env_file:
      - ./.env

    ports:
      - '80:80'

volumes:
  postgres_data: