version: '3.3'

services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env

  api:
    build: ./password/

    restart: always

    depends_on:
      - db

    env_file:
      - ./.env

    ports:
      - '8000:8000'

volumes:
  postgres_data: